name: Java CI

on:
  [workflow_dispatch, push]
concurrency: ci-${{ github.ref }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with coverage
      run: ./gradlew test jacocoTestReport

    - name: Check coverage
      run: |
        COVERAGE=$(./gradlew jacocoTestReport | grep "Instruction Coverage" | grep -oP '\d+.\d')
        if (( $(echo "$COVERAGE < 85" | bc -l) )); then echo "Test coverage is less than 85%"; exit 1; fi

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
