name: DEPLOY

on:
    [workflow_dispatch, push]
concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: my-app:latest

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 --name my-app my-app:latest

    - name: Run JMeter tests
      run: |
        docker run --network host -v ${PWD}/jmeter:/jmeter -w /jmeter justb4/jmeter:latest -n -t ./test-plan.jmx
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: ./jmeter/results.csv
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # - name: Push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: my-app:latest
